// A fixture report with one green, one yellow, and one red claim, used to assert the
// honest-negative rendering.

export const API = 'http://localhost:9999';

export const FIXTURE_REPORT = {
  id: 'r1',
  job_id: 'j1',
  memo_hash: 'h',
  model_versions: { judge: 'claude-opus-4-8' },
  rubric_version: '1',
  summary_counts: {
    total: 3,
    by_traffic_light: { green: 1, yellow: 1, red: 1 },
    routed_to_review: 2,
  },
  unclaimed_spans: [],
  created_at: '2026-07-04T00:00:00Z',
  claims: [
    {
      id: 'c1',
      ordinal: 0,
      text: 'TP53 is a tumour suppressor.',
      cited_ids: [{ id_type: 'pmid', value: '12345' }],
      citation_checks: [
        {
          identifier: 'pmid:12345',
          id_type: 'pmid',
          resolution_status: 'ok',
          source_status: 'active',
          title_match: 'not_applicable',
          author_match: 'true',
          year_match: 'true',
          resolver_path: 'esummary',
        },
      ],
      retrieval_mode: 'cited_fulltext',
      evidence: { evidence_sentence: 'TP53 is a tumour suppressor.', source_locator: {}, evidence_not_located: false },
      verdict: { label: 'supported', confidence: 0.95, rationale: 'stated' },
      category: 'mechanistic',
      diagnostic: 'D1',
      traffic_light: 'green',
      auto_pass_blocked: false,
      auto_passed: true,
      routed_to_review: false,
      reviewer_actions: [],
      effective_verdict: { label: 'supported', confidence: 0.95, rationale: 'stated' },
      effective_traffic_light: 'green',
      reviewed: false,
      reviewed_by: null,
      reviewed_at: null,
      review_action: null,
    },
    {
      id: 'c2',
      ordinal: 1,
      text: 'The proposed mechanism is not located in the retrieved text.',
      cited_ids: [],
      citation_checks: [],
      retrieval_mode: 'none',
      evidence: { evidence_sentence: null, source_locator: null, evidence_not_located: true },
      verdict: null,
      category: 'mechanistic',
      diagnostic: 'D3',
      traffic_light: 'yellow',
      auto_pass_blocked: true,
      auto_passed: false,
      routed_to_review: true,
      reviewer_actions: [],
      effective_verdict: null,
      effective_traffic_light: 'yellow',
      reviewed: false,
      reviewed_by: null,
      reviewed_at: null,
      review_action: null,
    },
    {
      id: 'c3',
      ordinal: 2,
      text: 'A result cited to a fabricated reference.',
      cited_ids: [{ id_type: 'pmid', value: '99999999' }],
      citation_checks: [
        {
          identifier: 'pmid:99999999',
          id_type: 'pmid',
          resolution_status: 'fabricated',
          source_status: null,
          title_match: 'not_applicable',
          author_match: 'not_applicable',
          year_match: 'not_applicable',
          resolver_path: 'esummary',
        },
      ],
      retrieval_mode: 'none',
      evidence: { evidence_sentence: null, source_locator: null, evidence_not_located: true },
      verdict: null,
      category: 'citation',
      diagnostic: 'D5',
      traffic_light: 'red',
      auto_pass_blocked: true,
      auto_passed: false,
      routed_to_review: true,
      reviewer_actions: [],
      effective_verdict: null,
      effective_traffic_light: 'red',
      reviewed: false,
      reviewed_by: null,
      reviewed_at: null,
      review_action: null,
    },
  ],
};
